language: rust
rust:
  - nightly

cache: cargo

script:
  - rustup install nightly-2020-01-02 && rustup default nightly-2020-01-02
  - rustc --version && rustup --version && cargo --version
  - cargo clean && cargo build --verbose --release
  - cargo test --verbose
