[package]
name = "vigil-server"
version = "0.0.4"
description = "Microservices Status Page. Monitors a distributed infrastructure and sends alerts to Slack."
readme = "README.md"
license = "MPL-2.0"
homepage = "https://github.com/valeriansaliou/vigil"
repository = "https://github.com/valeriansaliou/vigil.git"
keywords = ["microservices", "infrastructure", "status", "monitor", "slack"]
categories = ["web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>"]
exclude = ["dev/*"]

[badges]
travis-ci = { repository = "valeriansaliou/vigil", branch = "master" }
coveralls = { repository = "valeriansaliou/vigil", branch = "master", service = "github" }

[[bin]]
name = "vigil"
path = "src/main.rs"
doc = false

[dependencies]
log = "0.3"
clap = { version = "2.29", default-features = false }
lazy_static = "1.0"
interpolate_idents = "0.2"
time = "0.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
url_serde = { version = "0.2", default-features = false }
ordermap = { version = "0.3", features = ["serde-1"] }
rocket = { version = "0.3", default-features = false }
rocket_codegen = "0.3"
rocket_contrib = { version = "0.3", features = ["tera_templates"] }
native-tls = "0.1"
reqwest = "0.8"
lettre = { version = "0.7", features = ["smtp-transport"] }
lettre_email = "0.7"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
